### ISSUE TITLE
Highlights keywords that do not exist

### ISSUE THREAD

**Issue by Nek-12** [SnipMeDev/Highlights#30]
Expression
```
val KOTLIN_KEYWORDS = JAVA_KEYWORDS + (...)
``` 

Is incorrect

There are no `byte, extends, implements, instanceof, native, strictfp, synchronized, throws, transient` keywords

Using c keywords for java (and Kotlin) is incorrect 
Using common keywords for java (Kotlin) is incorrect for the same reason

**Comment by tmaxxdd** [comment]
Hi @Nek-12 

Thanks for that suggestion. This will be hotfixed soon.

**Comment by tmaxxdd** [comment]
The assumption was too simplified. All keywords are fixed in  #35
