### ISSUE TITLE
Highlights keywords in the middle of a word

### ISSUE THREAD

**Issue by Nek-12** [SnipMeDev/Highlights#31]
To reproduce: 

Use Kotlin language, 

Highlight 

```
val intent = 0
```
Highlights "int" which is incorrect

**Comment by tmaxxdd** [comment]
Hi @Nek-12 
Please check that again. Probably after correcting keywords this may be fixed.

I added unit test to verify that case #37.
If this is still valid in any of your cases, please provide a unit test with reproduction.

**Comment by Nek-12** [comment]
Other test cases:
1. ```copy(input = input(intent.value)) // highlights "value"```

2. ![image](https://github.com/SnipMeDev/Highlights/assets/46318640/716179f0-5e85-44cd-ba3f-6ce74a2dc2ef)
   ```
        // calling configure() is equivalent to: {}
   ```
   <- brackets and "is" highlighted, curly braces highlighted in string templates, but 
   contents of templates not highlighted properly. 

3. `val new = 1` <- highlights "new"

4. `val initialPages = 0` <- highlights "init" , also `retainedStore(initial = Loading)`

**Comment by tmaxxdd** [comment]
Okay, 

Thanks, it turns out unit tests didn't cover some other more complex cases.

This will be improved for release 0.9.0

**Comment by tmaxxdd** [comment]
Please check #42 I have added some test code according to your previous comment.

**Comment by Nek-12** [comment]
Looks fine, I will take a look at 0.9.0. I'm suspicious of the `value` being a keyword. Value is only a keyword in specific places (class declaration scope)

**Comment by tmaxxdd** [comment]
@Nek-12 Yeah, I have removed the "value" keyword alone. It could lead to more problems than profits.
The 0.9.0 is released.
