### ISSUE TITLE
Update to compose 1.7.0

### ISSUE THREAD

**Issue by Nek-12** [SnipMeDev/Highlights#51]
We are affected by https://github.com/JetBrains/compose-multiplatform/issues/4277 because this lib depends on old compose version. Please make an update with CMP 1.7

**Comment by tmaxxdd** [comment]
@Nek-12 This library does not implement any of `compose` dependencies. Maybe you would like to post an issue to KodeView?

**Comment by Nek-12** [comment]
Oh yes, probably, but our build is failing because of org.jetbrains.annotations (which are the cause of the issue in CMP). Are you sure you're not using annotations anywhere that may conflict with other (compose) code?

**Comment by tmaxxdd** [comment]
@Nek-12 There is now a new #54 1.0.0 version with Kotlin 2.0 updated. Maybe sth has been updated under the hood? Please check this version

**Comment by Nek-12** [comment]
Is that one published somehow? How do we use it? Also, why not 2.0.20? We are using that one.

**Comment by tmaxxdd** [comment]
Kotlin 2.0.20 is no problem ;) I have packed the updated 1.0.0 version. You may try to include it via maven local
[highllights_1.0.0.zip](https://github.com/user-attachments/files/17003608/highllights_1.0.0.zip)

**Comment by tmaxxdd** [comment]
Kotlin 2.0.20 is available in the newest 1.0.0 version
